---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration-crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: migration-crd
    server: 'https://kubernetes.default.svc'
  project: migration-crd
  source:
    repoURL: git@github.com:ThomasHerve/migration-crd-helm.git
    path: root-app/prod
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - Validate=true
  ignoreDifferences:
    # pod toleration causes a diff because the target cluster is different
    - group: ""
      kind: Pod
      jsonPointers:
        - /spec/tolerations
